---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache=yes

  - name: install tmux
    apt:
      name: tmux
      state: absent

  - name: install htop
    apt:
      name: htop
      state: absent
